### ISSUE TITLE
Errors installing on Meteor 1.4

### ISSUE THREAD

**Issue by rijk** [Semantic-Org/Semantic-UI-Meteor#100]
I'm still debugging to figure out what is happening, but so far I cannot get this package to build properly on Meteor 1.4. Did a clean install, following all the [instructions](https://github.com/Semantic-Org/Semantic-UI-Meteor#usage) to the letter (except for using `juliancwirko:postcss`; it's [not supported on 1.4](https://github.com/juliancwirko/meteor-postcss) so instead I used `lauricio:less-autoprefixer@2.5.0_3`, which works for me in another project). Used the generated options in `custom.semantic.json` to make sure I wasn't missing a key definition.

The strange thing is, it _has_ worked for a little while when I copied the entire `client/lib/semantic-ui` folder from a different project. It only broke after changing the variables a couple of times (not immediately the first time). So there's definitely something going wrong in Meteor's build process. Maybe some attempted optimisation in 1.4, of not processing all the files?

Here's the error:

```
=> App running at: http://localhost:3000/     
=> Errors prevented startup:                  

   While minifying app stylesheet:

   /Users/Rijk/.meteor/packages/standard-minifier-css/.1.1.8.1ssx8kx++os+web.browser+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifyStdCSS/node_modules/source-map/lib/array-set.js:79:11:
   "client/lib/semantic-ui/theme.import.less" is not in the set.
   at ArraySet_indexOf
   (/Users/Rijk/.meteor/packages/standard-minifier-css/.1.1.8.1ssx8kx++os+web.browser+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifyStdCSS/node_modules/source-map/lib/array-set.js:79:11)
   at SourceMapGenerator_serializeMappings
   (/Users/Rijk/.meteor/packages/standard-minifier-css/.1.1.8.1ssx8kx++os+web.browser+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifyStdCSS/node_modules/source-map/lib/source-map-generator.js:322:37)
   at SourceMapGenerator_toJSON
   (/Users/Rijk/.meteor/packages/standard-minifier-css/.1.1.8.1ssx8kx++os+web.browser+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifyStdCSS/node_modules/source-map/lib/source-map-generator.js:372:24)
   at SourceMapGenerator_toString
   (/Users/Rijk/.meteor/packages/standard-minifier-css/.1.1.8.1ssx8kx++os+web.browser+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifyStdCSS/node_modules/source-map/lib/source-map-generator.js:392:34)
   at packages/minifyStdCSS/plugin/minify-css.js:125:1
   at CssToolsMinifier.processFilesForBundle (packages/minifyStdCSS/plugin/minify-css.js:17:1)


=> Your application has errors. Waiting for file change.

```

**Comment by rijk** [comment]
Appears to be an issue with `lauricio:less-autoprefixer`. After switching to `flemay:less-autoprefixer` the problem went away (although I had to reorganize my app, because flemay:less-autoprefixer doesn't support cross-package imports).
