### ISSUE TITLE
Crashing while going through the start up guide

### ISSUE THREAD

**Issue by jeremywrnr** [Semantic-Org/Semantic-UI-Meteor#126]
While trying to just work through the starting guide, adding Semantic keeps crashing meteor. The app was working well before adding this packatge. Here is the error log:

	Errors prevented startup:
	
	While processing files with less (for target web.browser):
	semantic/src/definitions/collections/breadcrumb.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/collections/form.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/collections/grid.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/collections/menu.less:20: Unknown import: ../../theme.config
	semantic/src/definitions/collections/message.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/collections/table.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/elements/button.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/elements/container.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/elements/divider.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/elements/flag.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/elements/header.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/elements/icon.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/elements/image.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/elements/input.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/elements/label.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/elements/list.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/elements/loader.less:17: Unknown import: ../../theme.config
	semantic/src/definitions/elements/rail.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/elements/reveal.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/elements/segment.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/elements/step.less:23: Unknown import: ../../theme.config
	semantic/src/definitions/globals/reset.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/globals/site.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/modules/accordion.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/modules/checkbox.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/modules/dimmer.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/modules/dropdown.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/modules/embed.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/modules/modal.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/modules/nag.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/modules/popup.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/modules/progress.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/modules/rating.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/modules/search.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/modules/shape.less:20: Unknown import: ../../theme.config
	semantic/src/definitions/modules/sidebar.less:20: Unknown import: ../../theme.config
	semantic/src/definitions/modules/sticky.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/modules/tab.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/modules/transition.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/views/ad.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/views/card.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/views/comment.less:19: Unknown import: ../../theme.config
	semantic/src/definitions/views/feed.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/views/item.less:18: Unknown import: ../../theme.config
	semantic/src/definitions/views/statistic.less:18: Unknown import: ../../theme.config
	semantic/src/theme.less:26: Unknown import: themes/default/globals/site.variables
	
	While minifying app stylesheet:
	path.js:8:11: Path must be a string. Received null
	  at assertPath (path.js:8:11)
	  at Object.posix.relative (path.js:496:3)
	  at pathRelative (packages/minifier-css.js:449:30)
	  at packages/minifier-css.js:408:31
	  at Array.forEach (native)
	  at Function._.each._.forEach (packages/underscore.js:139:11)
	  at packages/minifier-css.js:365:7
	  at Array.forEach (native)
	  at Function._.each._.forEach (packages/underscore.js:139:11)
	  at rewriteRules (packages/minifier-css.js:342:5)
	  at Object.CssTools.rewriteCssUrls (packages/minifier-css.js:328:5)
	  at packages/minifier-css.js:298:16
	  at Array.forEach (native)
	  at Function._.each._.forEach (packages/underscore.js:139:11)
	  at Object.CssTools.mergeCssAsts (packages/minifier-css.js:275:7)
	  at mergeCss (packages/minifier-postcss/plugin/minify-css.js:231:33)
	  at CssToolsMinifier.processFilesForBundle (packages/minifier-postcss/plugin/minify-css.js:109:18)
	
	
	Your application has errors. Waiting for file change.

**Comment by nooitaf** [comment]
Is there a chance you started the app from outside the apps root directory? 
We might have to clarify it in the docs or fix it somehow : \

**Comment by jeremywrnr** [comment]
Hmmm it has been a while but I don't think so - it would have not worked otherwise. The app was working before adding this package, so instead I just added the files to `public/` and then linked to them from there and it worked fine, but that way is much messier. Thanks for getting back to me though!

**Comment by nooitaf** [comment]
np, but i might add that meteor apps (just like git) usually work even inside a subfolder
