### ISSUE TITLE
semantic-ui NEEDS to be placed in /lib/client/ ?

### ISSUE THREAD

**Issue by kosirdavid** [Semantic-Org/Semantic-UI-Meteor#41]
Hello,

I'm new with Meteor and have little experience with Semantic-ui.
I've tried to install Semantic-ui in `PROJECT_ROOT/semantic/` directory, but I got errors:

```
$ meteor
[[[[[ ~/web/meteor/luna ]]]]]     

=> Started proxy.                             
=> Started MongoDB.                           
W20150717-14:01:36.367(2)? (STDERR)           
W20150717-14:01:36.369(2)? (STDERR) /home/david/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150717-14:01:36.369(2)? (STDERR)                         throw(ex);
W20150717-14:01:36.369(2)? (STDERR)                               ^
W20150717-14:01:36.369(2)? (STDERR) ReferenceError: jQuery is not defined
W20150717-14:01:36.369(2)? (STDERR)     at app/semantic/definitions/behaviors/api.js:1081:5
W20150717-14:01:36.369(2)? (STDERR)     at app/semantic/definitions/behaviors/api.js:1083:3
W20150717-14:01:36.369(2)? (STDERR)     at /home/david/web/meteor/luna/.meteor/local/build/programs/server/boot.js:222:10
W20150717-14:01:36.369(2)? (STDERR)     at Array.forEach (native)
W20150717-14:01:36.370(2)? (STDERR)     at Function._.each._.forEach (/home/david/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150717-14:01:36.370(2)? (STDERR)     at /home/david/web/meteor/luna/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
W20150717-14:01:41.987(2)? (STDERR)           
W20150717-14:01:41.987(2)? (STDERR) /home/david/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150717-14:01:41.988(2)? (STDERR)                         throw(ex);
W20150717-14:01:41.988(2)? (STDERR)                               ^
W20150717-14:01:41.992(2)? (STDERR) ReferenceError: jQuery is not defined
W20150717-14:01:41.992(2)? (STDERR)     at app/semantic/definitions/behaviors/api.js:1081:5
W20150717-14:01:41.992(2)? (STDERR)     at app/semantic/definitions/behaviors/api.js:1083:3
W20150717-14:01:41.992(2)? (STDERR)     at /home/david/web/meteor/luna/.meteor/local/build/programs/server/boot.js:222:10
W20150717-14:01:41.992(2)? (STDERR)     at Array.forEach (native)
W20150717-14:01:41.992(2)? (STDERR)     at Function._.each._.forEach (/home/david/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150717-14:01:41.992(2)? (STDERR)     at /home/david/web/meteor/luna/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
W20150717-14:01:47.405(2)? (STDERR)           
W20150717-14:01:47.405(2)? (STDERR) /home/david/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150717-14:01:47.406(2)? (STDERR)                         throw(ex);
W20150717-14:01:47.406(2)? (STDERR)                               ^
W20150717-14:01:47.408(2)? (STDERR) ReferenceError: jQuery is not defined
W20150717-14:01:47.408(2)? (STDERR)     at app/semantic/definitions/behaviors/api.js:1081:5
W20150717-14:01:47.408(2)? (STDERR)     at app/semantic/definitions/behaviors/api.js:1083:3
W20150717-14:01:47.409(2)? (STDERR)     at /home/david/web/meteor/luna/.meteor/local/build/programs/server/boot.js:222:10
W20150717-14:01:47.409(2)? (STDERR)     at Array.forEach (native)
W20150717-14:01:47.409(2)? (STDERR)     at Function._.each._.forEach (/home/david/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150717-14:01:47.409(2)? (STDERR)     at /home/david/web/meteor/luna/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

Then I made `PROJECT_ROOT/lib/client/semantic-ui` and installation went well.

I guess that is a bug, right?

**Comment by nooitaf** [comment]
It's not a bug. If you dont put client code into a `/client/` folder meteor will try to load it on the client and the server and the server does not have jQuery. The `/client/lib/` folder contents will be loaded first before other files in the `/client/` folder.

Somehow related to https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/32#issuecomment-120633493

**Comment by kosirdavid** [comment]
Thanks @nooitaf for quick explanation, it makes sense.

Maybe you could update README that says:
`create an empty custom.semantic.json file somewhere in your project.`
into something that is not misleading for new uses.
