### ISSUE TITLE
need to depend on jquery

### ISSUE THREAD

**Issue by reimertz** [Semantic-Org/Semantic-UI-Meteor#70]
Just tried the most recent update in hopes that build times would improve, but I got this error now.
Seems that we forgot to add  jquery as a dependency in packages.js ?

```
W20151010-11:15:32.591(-7)? (STDERR) ReferenceError: jQuery is not defined
W20151010-11:15:32.591(-7)? (STDERR)     at definitions/behaviors/api.js:1140:5
W20151010-11:15:32.591(-7)? (STDERR)     at /Users/reimertz/heartcoins/hc-meteor-new/.meteor/local/build/programs/server/app/definitions/behaviors/api.js:981:4
W20151010-11:15:32.591(-7)? (STDERR)     at /Users/reimertz/heartcoins/hc-meteor-new/.meteor/local/build/programs/server/boot.js:242:10
```

**Comment by reimertz** [comment]
I fuxxed up, I put my custom.semantic.json in root so that caused semantic to be available on both client and server. :sob:
